# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='scores',
            field=models.TextField(default=''),
        ),
    ]
